name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build the code
      - name: build
        run: gcc main.c -g -o example

      # Upload the binary, which we will need to debug the core
      - uses: actions/upload-artifact@v3
        with:
          name: executable
          path: ./example

      - name: Set cores to get stored in /cores
        run:
          sudo mkdir /cores
          sudo chmod 777 /cores
          sudo echo "/cores/%e.%p.%t" > /proc/sys/kernel/core_pattern
          
      - name: Run the binary
        run: |
          # Allow core dumps
          ulimit -c unlimited
          # Run the program, triggering core dump
          ./example

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}  # Run only if something went wrong
        with:
          name: cores
          path: /cores
